### PR TITLE
fix: subMessage not populated

### PR DESCRIPTION
**Pull request by FineWolf**
### Description of the Change
The subscription message is not being populated at the moment due to a difference between what the event data provides(`subMessage`) and what the built-in expects (`message`).

This PR implements the following:
- Use `subMessage` in the built-in variable evaluation to return the actual message.
- Populate `subMessage` when triggering an event manually for testing.
- Normalize `cheer` event so that is uses `cheerMessage` instead of `message` (all the other event uses distinct names for their message property [ie.: `subMessage`, `chatMessage`, etc....])

### Applicable Issues
N/A - Didn't open an issue for this bug.

### Testing
Tested receiving subs via Twitch + test triggers.

### Screenshots
No UI change applicable.

### CODE REVIEW

**Comment by CaveMobster** [comment]
Just a note: it's probably good to check PRs and tickets (although for the sub message there wasn't one), to see if someone was already working on something. I already put in a PR for the sub message fix, but the others are good catches too!

**Comment by FineWolf** [comment]
The worst part is that I did search both issues and PRs, I can't believe I missed yours @CaveMobster . I must have searched PRs for `subMessage` without a space 🤦🏻‍♂️.

I'm really sorry I missed your PR.

**Comment by CaveMobster** [comment]
Oh no worries at all! I think it's a good reminder for me to make tickets whenever I work on something. You don't have to close this one, I think it's easier that I close mine and refer to this one, which is no problem. Thank you for helping out!

**Comment by FineWolf** [comment]
I've changed the base branch for my commit to `v5` as per the other pull requests in this repo.

**Review by ebiggz — APPROVED** [review]
Looks great. Thanks for taking the time to look into this!

**Pull request merged**
