### PR TITLE
Theme support for background color on more elements

### PR DESCRIPTION
**Pull request by fluxstorm0**
### Description of the Change
Effect list options and chat alerts were not displaying the proper colors based on selected color scheme. Slightly expanded support of the theme system to support background colors for chat alerts and effect list items.

### Applicable Issues
N/A

### Testing
Manual testing by choosing each theme to verify the modified elements are properly displayed.

### Screenshots
image
image

### CODE REVIEW

**Comment by Oceanity** [comment]
Target branch should be v5, not master :P

**Comment by VisitingOcean** [comment]
> Target branch should be v5, not master :P

👍 - I also found another background to fix so I will close this and reopen targeting v5 and with the new fix.

Thanks!

**Comment by Oceanity** [comment]
> > Target branch should be v5, not master :P
> 
> 👍 - I also found another background to fix so I will close this and reopen targeting v5 and with the new fix.
> 
> Thanks!

You don't have to close it, you can edit the target branch, and you can push commits to this without making a new one, better practice to keep the conversations around!

**Comment by Oceanity** [comment]
Just to show how to do it 😛

https://github.com/user-attachments/assets/97b5d8fd-3479-45db-b342-b6425d0d0dcb

**Review by itsjesski — APPROVED** [review]

**Pull request merged**
