### PR TITLE
feat: color variable

### PR DESCRIPTION
**Pull request by CKY-**
### Description of the Change

adds color variable with conversion to and from all easy to convert formats 
hsl to hex
hex to hsl 
color name to any 
rgb 
hsv 
                examples: 

                usage: 'color[red]',
                description: "returns '#ff0000'"

                usage: 'color[red, hex]',
                description: "returns '#ff0000'"
      
                usage: 'color[red, hexa, 255]',
                description: "returns '#ff0000ff'"

                usage: 'color[green, ahex, 255]',
                description: "returns '#ff00ff00'"

                usage: 'color[green, ahex, 20]',
                description: "returns '#2000ff00'"

                usage: 'color[red, rgb]',
                description: "returns 'rgb(255, 0, 0)'"
   
                usage: 'color[red, rgbp]',
                description: "returns 'rgb(100%, 0, 0)'"

                usage: 'color[#00ff00, hsl]',
                description: "returns 'hsl(0, 100%, 50%)'"

                usage: 'color[#ff00ff00, hsv, 0.5]',
                description: "returns 'hsv(0, 100%, 100%)'"

                usage: 'color[#ff00ff00, dec]',
                description: "returns decimal value"
     
there are many more things that can be done with this 
turning RGB to hex   'color[RGB(255, 0, 0)]' returns ff0000ff

### Applicable Issues

#2076

### Testing

I have had and used this in a script for a very long time I am adding it to the code base at the request of @dennisrijsdijk 
I use this to control my WiZ lights color from chat, my clock color, and my clouds, the clouds are in hsl and the clock is in hsv
the WiZ lights are in hsv as well but everything else is in hex8 formats.

I now need someone with Elgato Strip lights and Phillips Hue to test this.

### CODE REVIEW

**Comment by dennisrijsdijk** [comment]
I feel it might be helpful to add a text example of the possible usages *without* values. Eg, I find it very unclear what `color[green, ahex, 20]` does just from reading the usage

**Comment by CKY-** [comment]
@dennisrijsdijk thats in the description.

**Comment by CKY-** [comment]
The string parsing is very permissive. It is meant to make typing a color as input as easy as possible. All commas, percentages, parenthesis are optional, and most input allow either 0-1, 0%-100%, or 0-n (where n is either 100, 255, or 360 depending on the value).

HSL and HSV both require either 0%-100% or 0-1 for the S/L/V properties. The H (hue) can have values between 0%-100% or 0-360.

RGB input requires either 0-255 or 0%-100%.

Here are **some** examples of string input:

### Hex, 8-digit (RGBA) Hex

color["#000"]
color["000"]
color["#369C"]
color["369C"]
color["#f0f0f6"]
color["f0f0f6"]
color["#f0f0f688"]
color["f0f0f688"]

### RGB, RGBA

color["rgb (255, 0, 0)"]
color["rgb 255 0 0"]
color["rgba (255, 0, 0, .5)"]
color[{ r: 255, g: 0, b: 0 }]


### HSL, HSLA

color["hsl(0, 100%, 50%)"]
color["hsla(0, 100%, 50%, .5)"]
color["hsl(0, 100%, 50%)"]
color["hsl 0 1.0 0.5"]
color[{ h: 0, s: 1, l: .5 }]


### HSV, HSVA

color["hsv(0, 100%, 100%)"]
color["hsva(0, 100%, 100%, .5)"]
color["hsv (0 100% 100%)"]
color["hsv 0 1 1"]
color[{ h: 0, s: 100, v: 100 }]


### Named

Case insenstive names are accepted, using the  [list of colors in the CSS spec](https://www.w3.org/TR/css-color-4/#named-colors).

color["RED"]
color["blanchedalmond"]
color["darkblue"]

the output is selected by specifying the type in the second parameter the alpha is controlled by the third parameter 
color[#F00, rgb, 124]
will output rgb(255, 0, 0, 0.5)

**Comment by itsjesski** [comment]
Is the "needs review" tag saying that this is still in testing? I'm not going to merge until everything is good.

**Comment by dennisrijsdijk** [comment]
This requires testing from Elgato lights and Philips Hue before merge

**Comment by CKY-** [comment]
> Is the "needs review" tag saying that this is still in testing? I'm not going to merge until everything is good.
Elgato Strip lights and Phillips Hue got changed. we can move this into v5 but I would like someone with the hardware confirm that I did not break anything.

**Pull request merged**
