### PR TITLE
Update all twitch packages to the new major version

### PR DESCRIPTION
**Pull request by CaveMobster**
### Description of the Change
This PR updates the Twitch API, PubSub and Chat packages to the newest version, and it adds an Auth package.

### Applicable Issues
https://github.com/crowbartools/Firebot/issues/1374

### Testing
I've tested the authentication, all API usages and the chat usages. PubSub remains to be seen. (yay beta!) I also tested the pubsub and chat connections.

### CODE REVIEW

**Comment by ebiggz** [comment]
Changed the PR branch to Master so it triggers the beta release build.

**Review by ebiggz — APPROVED** [review]
Looks awesome, this will be huge!

**Review by ebiggz — CHANGES_REQUESTED** [review]
Oh wait we don't want to merge this into master yet as the `version` in the package json doesn't have the beta suffix in it yet.

**Comment by CaveMobster** [comment]
> 
> 
> Oh wait we don't want to merge this into master yet as the `version` in the package json doesn't have the beta suffix in it yet.

Oh right, I'll do that now.

**Review by ebiggz — APPROVED** [review]

**Pull request merged**
