### PR TITLE
css: Select Effect & Variables Theming

### PR DESCRIPTION
**Pull request by phroggster**
### Description of the Change

- Rewrite select effect modal and variable menu to use themes.
- This fixes a lot of (all?) hard-coded theming issues in these UIs.
- They sure are pretty now....

### Applicable Issues

N/A

### Testing

Tested as thoroughly as possible to have zero impact outside of these two interfaces, and tested the #$%& out of these two interfaces.

### Screenshots

Select new effect modal:
effects-again

Select variables menu:
vars

### CODE REVIEW

**Comment by phroggster** [comment]
@fluxstorm0 Please check this one over. It obliterates your work in #2815, but hopefully is a bit more encompassing. Sorry that we haven't been very good about light theme to date!

**Comment by phroggster** [comment]
Well, I'm stumped... The variables menu, magic category, "What are these?" tooltip link no longer functions after these changes. I'm not sure why this is the case, but I did in-fact break them somehow. Does anyone have any ideas?

**Comment by CKY-** [comment]
that blue is too blue

**Comment by Wrongtown** [comment]
> that blue is too blue

Hoping for more of a cornflower blue?

**Comment by phroggster** [comment]
All right, I've rolled back certain changes (the "blue," the category header opacity override, the clickable + noselect) and corrected the outstanding issues with this PR. The opacity override is what was causing issues with the disappearing tooltip.

I have updated the original comment's screen shots to be reflective of the current state of this PR, and formally submit it for acceptance.

**Review by heyaapl — APPROVED** [review]

**Pull request merged**
