### PR TITLE
Add a regex variable

### PR DESCRIPTION
**Pull request by CaveMobster**
### Description of the Change
This adds a variable to use regular expressions.

### Applicable Issues
n/a

### CODE REVIEW

**Review by ebiggz — CHANGES_REQUESTED** [review]
Great idea for a $variable. 

Based on feedback I got on the $textReplace variable which also supports regex, we will want to add the ability for the user to define regex flags too.

```js
evaluator: (_, stringToEvaluate, expression, flags) => {
        const regex = RegExp(expression, flags);
```

**Comment by CaveMobster** [comment]
Oh good point, thank you! Added this, and also changed the return value of `null` into a clear response message when no match is found.

**Comment by CaveMobster** [comment]
Updated as discussed on Discord.

**Review by ebiggz — APPROVED** [review]
Excellent, thanks for hashing out the details with me on this one 🥇

**Pull request merged**
