### PR TITLE
feat: Remember Active Dashboard Chat User, Message Text, and Replying-To

### PR DESCRIPTION
**Pull request by phroggster**
### Description of the Change

- Caches the active chat sender, outgoing chat message text, and reply/thread information in the dashboard when the chat-messages controller gets reloaded.
- This intentionally **does not** get saved to disk, and the application will always start back up with "Streamer" as the active chat sender.
- Does not add any actual settings, checkboxes, nor UI. It just remembers the thing you already changed while the application stays active.
- Previously, changing component tabs then changing back would cause the chat sender to get reset to Streamer, the message text to be blank, and the reply-to/thread information to be dropped. This was *not* cool.

### Applicable Issues

#2353

### Testing

Yup, video evidence of functionality:
[Video Of Tests](https://github.com/user-attachments/assets/befc6419-af88-44f3-a308-9f4d2a7ee129)

### Screenshots

N/A

### CODE REVIEW

**Comment by Wrongtown** [comment]
Nice one, I noticed this in my re-testing of changes for #2753 👍

**Review by ebiggz — CHANGES_REQUESTED** [review]
This is a much needed improvement, thanks for doing it!

One minor suggestion: since we just want to cache UI state in memory, I think it would make most sense to store the `chatSender` variable in the associated `chat-messages.service` instead of using the settings service. "Settings" in this context currently represents any user defined settings that we want to persist to file, so having a memory only setting here to store UI state feels outside the scope.  In the event we do want to persist the selected chatter to file though, we could move to using settings!

General implementation:
```js
// chat-messages.service.js
service.chatSender = "Streamer";
```

```js
// chat-messages.controller.js
$scope.setChatSender = function(chatter) {
    chatMessagesService.chatSender = chatter;
};
```

```html
<!-- _chat-messages.html (chat messages service already passed to scope as $scope.cms)  -->
<span class="ml-4" style="width: 100%; text-align: center">{{cms.chatSender}}</span>
```

**Comment by phroggster** [comment]
Thanks for the nudge away from `settingsService`, that did seem like the wrong place for this. I'm going to take your wisdom into account, but also add caching for any pending message text. The breadth of this PR has now been bumped up a notch, ever since I typed out a wordy message then switched tabs to look up an identifier and lost my message text the other day. 😭

Should have this PR updated within a few hours.

**Review by ebiggz — APPROVED** [review]
Ooo great idea to update reply-to and message text as well. This will be so nice. Thanks for rockin' this!

**Pull request merged**
